[2021-05-30 00:02:06,433] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: iraq_scoring_report.append_days 2021-05-29T00:00:00+00:00 [queued]>
[2021-05-30 00:02:06,649] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: iraq_scoring_report.append_days 2021-05-29T00:00:00+00:00 [queued]>
[2021-05-30 00:02:06,650] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-30 00:02:06,650] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-05-30 00:02:06,651] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-30 00:02:07,060] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): append_days> on 2021-05-29T00:00:00+00:00
[2021-05-30 00:02:07,375] {standard_task_runner.py:52} INFO - Started process 44 to run task
[2021-05-30 00:02:07,400] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'iraq_scoring_report', 'append_days', '2021-05-29T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/iraq_dag.py', '--cfg-path', '/tmp/tmpl281v698', '--error-file', '/tmp/tmpqibrauae']
[2021-05-30 00:02:07,403] {standard_task_runner.py:77} INFO - Job 9: Subtask append_days
[2021-05-30 00:02:07,894] {logging_mixin.py:104} INFO - Running <TaskInstance: iraq_scoring_report.append_days 2021-05-29T00:00:00+00:00 [running]> on host abadef31f2e2
[2021-05-30 00:02:08,127] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Asma
AIRFLOW_CTX_DAG_ID=iraq_scoring_report
AIRFLOW_CTX_TASK_ID=append_days
AIRFLOW_CTX_EXECUTION_DATE=2021-05-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-29T00:00:00+00:00
[2021-05-30 00:02:08,870] {taskinstance.py:1455} ERROR - 'PythonOperator' object is not callable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/iraq_dag.py", line 47, in append_days
    for Day in list_days():
TypeError: 'PythonOperator' object is not callable
[2021-05-30 00:02:09,014] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=iraq_scoring_report, task_id=append_days, execution_date=20210529T000000, start_date=20210530T000206, end_date=20210530T000209
[2021-05-30 00:02:09,603] {local_task_job.py:146} INFO - Task exited with return code 1
